name: 'Build Test'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - shell: bash
      run: |
        npm install
        npm build
