version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5437:5432'
    volumes:
      - pg-data:/data/postgres
    environment:
      - POSTGRES_USER=indexer
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=indexer

  indexer:
    build:
      context: .
      args:
        - NODE_ENV=development
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    deploy:
      resources:
        limits:
          memory: 2000M
        reservations:
          cpus: '0.1'
          memory: 2000M

volumes:
  pg-data:
