#!/bin/sh

cat << EOF > .env

LOG_LEVEL=${LOG_LEVEL:=info}

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}
AWS_BUCKET=${AWS_BUCKET}

DATABASE_TYPE=postgres
DATABASE_HOST=${DATABASE_HOST}
DATABASE_PORT=${DATABASE_PORT}
DATABASE_USERNAME=${DATABASE_USERNAME}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
DATABASE_NAME=${DATABASE_NAME}

START_BLOCK_HEIGHT=${START_BLOCK_HEIGHT}
LOOK_BACK_BLOCKS=${LOOK_BACK_BLOCKS}
FETCH_MAX_KEYS=${FETCH_MAX_KEYS}
BLOCKS_DL_CONCURRENCY=${BLOCKS_DL_CONCURRENCY}
WAIT_FOR_NEW_BLOCKS=${WAIT_FOR_NEW_BLOCKS}

TRACK_ACCOUNTS=${TRACK_ACCOUNTS}

EOF

npm run schema:sync
npm run migration:run
npm run build:start
